locale                   : "en-US"
site_theme               : "default"
title                    : "Kangmin Kim"
title_separator          : "-"
name                     : "Kangmin Kim"
description              : "AI | Machine Learning | Semiconductor Portfolio"

url                      : "https://goodpersongoodtime.github.io"
baseurl                  : ""
repository               : "goodpersongoodtime/goodpersongoodtime.github.io"

author:
  avatar           : "profile.png"
  name             : "Kangmin Kim"
  bio              : "B.S. Candidate in Systems Management Engineering | AI & Semiconductor"
  location         : "Suwon, Republic of Korea"
  employer         : "Sungkyunkwan University"
  email            : "Kang_min_kim@naver.com"

  github           : "goodpersongoodtime"
  linkedin         :
